apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  PORT: "3006"
  DB_HOST: "inventory-db" 
  DB_PORT: "5432"         
  DB_NAME: "inventory"     
  RABBITMQ_URL: "amqp://rabbitmq" 
