apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.order.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.order.dbPassword | quote }}
