apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  PORT: {{ .Values.inventory.service.port | quote }}
  DB_HOST: "inventory-db"
  DB_PORT: {{ .Values.inventory.db.port | quote }}
  DB_NAME: {{ .Values.secrets.inventory.dbName | quote }}