apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.inventory.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.inventory.dbPassword | quote }}
