apiVersion: v1
kind: Service
metadata:
  name: voltrico-inventory-service
spec:
  selector:
    app: voltrico-inventory-service
  ports:
    - port: {{ .Values.inventory.service.port }}
      targetPort: {{ .Values.inventory.service.port }}
  type: ClusterIP
