apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltrico-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voltrico-user-service
  template:
    metadata:
      labels:
        app: voltrico-user-service
    spec:
      containers:
      - name: user-service
        image: eloritz/voltrico-user-service:latest
        ports:
          - containerPort: 3002
        envFrom:
          - configMapRef:
              name: user-config
        env:
          - name: TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: TOKEN_SECRET
                
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: GOOGLE_CLIENT_ID
