apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: voltrico-user-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: voltrico-user-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: TOKEN_SECRET
      remoteRef:
        key: secret/user-service
        property: TOKEN_SECRET
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: secret/user-service
        property: GOOGLE_CLIENT_ID
    - secretKey: USER_DB_CONNECTION
      remoteRef:
        key: secret/user-service
        property: USER_DB_CONNECTION