apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: voltrico-cart-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: voltrico-cart-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: CART_DB_CONNECTION
      remoteRef:
        key: secret/cart-service
        property: CART_DB_CONNECTION