apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: {{ .Values.secrets.mongo.rootUser | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.secrets.mongo.rootPassword | quote }}
