apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: voltrico-rabbitmq-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: voltrico-rabbitmq-secrets
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: secret/rabbitmq
        property: RABBITMQ_DEFAULT_USER
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: secret/rabbitmq
        property: RABBITMQ_DEFAULT_PASS