apiVersion: v1
kind: ConfigMap
metadata:
  name: voltrico-order-service-config
data:  
  ORDER_SERVICE_PORT: "3005"
  ORDER_SERVICE_URL: "http://order-service:3005"
  ORDER_DB_HOST: "order-db"
  ORDER_DB_PORT: "5432"
  NOTIFICATIONS_QUEUE: "NOTIFICATIONS_QUEUE"
