apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  # Application Port
  PORT: "3005"
  
  # Database Connection Details (Host and Port)
  DB_HOST: "order-db" 
  DB_PORT: "5432"     
  
  # Messaging Queue URL
  RABBITMQ_URL: "amqp://rabbitmq" 
  DB_NAME: "orders" 