apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: voltrico-order-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: voltrico-order-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: ORDER_DB_USER
      remoteRef:
        key: secret/order-service
        property: ORDER_DB_USER
    - secretKey: ORDER_DB_PASSWORD
      remoteRef:
        key: secret/order-service
        property: ORDER_DB_PASSWORD
    - secretKey: ORDER_DB_NAME
      remoteRef:
        key: secret/order-service
        property: ORDER_DB_NAME