apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
stringData:
  TOKEN_SECRET: {{ .Values.secrets.user.tokenSecret | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.user.googleClientId | quote }}
