apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-db
spec:
  serviceName: "order-db"
  replicas: {{ .Values.order.db.replicas }}
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: order-db
        image: {{ .Values.order.db.image }}
        ports:
        - containerPort: {{ .Values.order.db.port }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          value: {{ .Values.order.db.dbName }}
        volumeMounts:
        - name: order-db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: order-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.order.db.storage }}
