apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: voltrico-product-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: voltrico-product-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: PRODUCT_DB_CONNECTION
      remoteRef:
        key: secret/product-service
        property: PRODUCT_DB_CONNECTION