apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
type: Opaque
stringData:
  username: {{ .Values.secrets.inventory.dbUser | quote }}
  password: {{ .Values.secrets.inventory.dbPassword | quote }}
  dbname: {{ .Values.secrets.inventory.dbName | quote }}
