apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltrico-product-service
spec:
  replicas: {{ .Values.product.replicas }}
  selector:
    matchLabels:
      app: voltrico-product-service
  template:
    metadata:
      labels:
        app: voltrico-product-service
    spec:
      containers:
        - name: voltrico-product-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.product.image }}:{{ .Values.product.tag }}"
          ports:
            - containerPort: {{ .Values.product.port }}
          envFrom:
            - configMapRef:
                name: product-config
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@rabbitmq:5672"
