apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltrico-cart-service
spec:
  replicas: {{ .Values.cart.replicas }}
  selector:
    matchLabels:
      app: voltrico-cart-service
  template:
    metadata:
      labels:
        app: voltrico-cart-service
    spec:
      containers:
        - name: voltrico-cart-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.cart.image }}:{{ .Values.cart.tag }}"
          ports:
            - containerPort: {{ .Values.cart.port }}
          envFrom:
            - configMapRef:
                name: cart-config
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@rabbitmq:5672"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltrico-product-service
spec:
  replicas: {{ .Values.product.replicas }}
  selector:
    matchLabels:
      app: voltrico-product-service
  template:
    metadata:
      labels:
        app: voltrico-product-service
    spec:
      containers:
        - name: voltrico-product-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.product.image }}:{{ .Values.product.tag }}"
          ports:
            - containerPort: {{ .Values.product.port }}
          envFrom:
            - configMapRef:
                name: product-config
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@rabbitmq:5672"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltrico-search-service
spec:
  replicas: {{ .Values.search.replicas }}
  selector:
    matchLabels:
      app: voltrico-search-service
  template:
    metadata:
      labels:
        app: voltrico-search-service
    spec:
      containers:
        - name: voltrico-search-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.search.image }}:{{ .Values.search.tag }}"
          ports:
            - containerPort: {{ .Values.search.port }}
          envFrom:
            - configMapRef:
                name: search-config
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@rabbitmq:5672"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltrico-api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      app: voltrico-api-gateway
  template:
    metadata:
      labels:
        app: voltrico-api-gateway
    spec:
      containers:
        - name: voltrico-api-gateway
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.apiGateway.image }}:{{ .Values.apiGateway.tag }}"
          ports:
            - containerPort: {{ .Values.apiGateway.port }}
          envFrom:
            - configMapRef:
                name: api-gateway-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltrico-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: voltrico-web
  template:
    metadata:
      labels:
        app: voltrico-web
    spec:
      containers:
        - name: voltrico-web
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.web.image }}:{{ .Values.web.tag }}"
          ports:
            - containerPort: {{ .Values.web.containerPort }}
          envFrom:
            - configMapRef:
                name: web-config