apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
type: Opaque
stringData:
  username: {{ .Values.secrets.inventory.dbUser | quote }}
  password: {{ .Values.secrets.inventory.dbPassword | quote }}
  dbname: {{ .Values.secrets.inventory.dbName | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.inventory.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.inventory.dbPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: {{ .Values.secrets.mongo.rootUser | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.secrets.mongo.rootPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  username: {{ .Values.secrets.order.dbUser | quote }}
  password: {{ .Values.secrets.order.dbPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.order.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.order.dbPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: voltrico-rabbitmq-secrets
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.rabbitmq.defaultUser | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmq.defaultPass | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
stringData:
  TOKEN_SECRET: {{ .Values.secrets.user.tokenSecret | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.user.googleClientId | quote }}
