apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
spec:
  serviceName: inventory-db
  replicas: {{ .Values.inventory.db.replicas }}
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
      - name: inventory-db
        image: {{ .Values.inventory.db.image }}
        ports:
        - containerPort: {{ .Values.inventory.db.port }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: dbname
        volumeMounts:
        - name: inventory-db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: inventory-db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.inventory.db.storage }}
