apiVersion: v1
kind: Service
metadata:
  name: inventory-db
spec:
  ports:
  - port: {{ .Values.inventory.db.port }}
    targetPort: {{ .Values.inventory.db.port }}
  clusterIP: None
  selector:
    app: inventory-db
