apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltrico-order-service
spec:
  replicas: {{ .Values.order.service.replicas }}
  selector:
    matchLabels:
      app: voltrico-order-service
  template:
    metadata:
      labels:
        app: voltrico-order-service
    spec:
      containers:
        - name: voltrico-order-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.order.service.image }}:{{ .Values.order.service.tag }}"
          ports:
            - containerPort: {{ .Values.order.service.port }}
          envFrom:
            - configMapRef:
                name: order-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: order-secret 
                  key: DB_USER       
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secret 
                  key: DB_PASSWORD 
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: voltrico-rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@rabbitmq:5672"