apiVersion: v1
kind: Secret
metadata:
  name: voltrico-rabbitmq-secrets
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.rabbitmq.defaultUser | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmq.defaultPass | quote }}
