apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: voltrico-web-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: voltrico-web-secrets
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_GOOGLE_CLIENT_ID
      remoteRef:
        key: secret/web
        property: NEXT_PUBLIC_GOOGLE_CLIENT_ID