apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voltrico-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: voltrico.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: voltrico-web
            port:
              number: 80
